### ISSUE TITLE
Can you upload video lecture of this course?

### ISSUE THREAD

**Issue by HuyNguyen97** [epfml/OptML_course#7]
Dear professor, Can you upload video lecture of this course?

Best regards.

**Comment by Pramodh-G** [comment]
Dear Professor, 

Making the lectures public will help a lot of students who want to get a leeway into this field, but are not able to due to constraints.

Since this contains, materials along with exercises, it is really useful for getting a practical and theoretical aspect of it.

Hoping that you would consider this request,
Pramodh

**Comment by martinjaggi** [comment]
ok, here it is:
https://www.youtube.com/playlist?list=PL4O4bXkI-fAeYrsBqTUYn2xMjJAqlFQzX
